# Generated by Django 3.0.6 on 2020-05-31 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('food_img', models.ImageField(upload_to='food_image/')),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=10)),
                ('f_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=80)),
                ('product_image', models.ImageField(upload_to='rest_img/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Register')),
                ('recipe', models.ManyToManyField(blank=True, to='blog.Food')),
            ],
        ),
        migrations.AddField(
            model_name='register',
            name='types',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.RegisterType'),
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Restaurant')),
                ('order', models.ManyToManyField(blank=True, to='blog.Food')),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='types',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.FoodType'),
        ),
    ]
